CREATE TABLE IF NOT EXISTS projects(
	`id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL UNIQUE,
    `description` TEXT NOT NULL,
    `course` VARCHAR(25),
    `startdate` DATE NOT NULL,
    `enddate` DATE,
    `url` VARCHAR(255),
    `servedurl` VARCHAR(255),
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS courses(
	`id` INT NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(10) UNIQUE NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `startdate` DATE NOT NULL,
    `enddate` DATE,
	`created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

