INSERT INTO projects (name, description, course_id, startdate, enddate, url)
VALUES ('Simple Programming Language', 'A simple, Pascal-like programming language created using C++ in CS280 (Programming Language Concepts).  Phase 1 consists only of the lexical analyzer which scans a text file and returns an error if a scanned lexeme does not match the specified grammar.  Phase 2 is the syntax analyzer (parser), and analyzes program statements.  This goes further than just reading each lexeme and verifying that the lexeme is valid within the programming language.  However, the parser cannot execute such statements yet.  Phase 3 is the final phase of the project and implements the interpreter.  This phase allows for actual execution of programs written using the simple language.  The interpreter can perform variable assignment, simple arithmetic (addition, subtraction, multiplication, and division), string concatenation, and if-else statements.',
        1, '2022-02-01', '2022-05-01', 'https://github.com/jbq2/PUBLIC-SimpProgLang');

INSERT INTO projects (name, description, course_id, startdate, enddate, url, servedurl)
VALUES ('Simple Online Shop', 'This project was a simple online shop full-stack project that was developed during my time taking IT202 (Internet Applications).  This website was developed using PHP, JS, CSS, and SQL.  The project focuses on full-stack concepts of website development.  The project was split into 4 milestones: milestone 1 for allowing user registration and admin roles, milestone 2 for building the shop page, milestone 3 for purchasing items, and milestone 4 for various areas of UI refactoring.  This project was quite large, so full documentation and a video demo is included in the GitHub repository for this project.',
        3, '2022-02-01', '2022-05-12', 'https://github.com/jbq2/IT202-010', 'https://jbq2-prod.herokuapp.com/Project/shop_page.php');

INSERT INTO projects (name, description, course_id, startdate, enddate, url)
VALUES ('Rent-A-Car Website', 'A car rental website based on a project assigned in CS331 (Database System Design and Management).  This website was developed similarly to the Simple Online Shop project, but with a larger focus on relational database concepts.  This project was split into 3 parts: part 1 for the conceptual design of the database (Entity Relationship Diagram) and mapping it to a relational schema, part 2 for creating the tables on Oracle and inserting sample data, and part 3 for normalizing the database and programming the website.  More documentation is included in the GitHub repository for this project.',
        2, '2022-03-01', '2022-05-04', 'https://github.com/jbq2/PUBLIC_CS331_RentACar');

INSERT INTO projects (name, description, startdate, url)
VALUES ('Personal Website', 'A personal blog website that displays information about myself and my projects.  This website will be served in the future and will be linked on my resume and other social media platforms that potential employers can see.  This is my first project utilizing tools and languages that are directly inline with my specific interests.  This website is currently being developed using Springboot and Angular. NOTE: there are currently 2 repositories for this project--the displayed GitHub link''s README will have the link to the other repository, and vice-versa.',
        '2022-06-12', 'https://github.com/jbq2/PersonalWebsiteFRONTEND');
